import type { TokenConfig, Timeframe } from '../types/crypto';

export const TOKENS: TokenConfig[] = [
  // Binance Tokens
  {
    id: 'sui',
    name: 'Sui',
    symbol: 'SUIUSDT',
    displaySymbol: 'SUI / USDT',
    baseAsset: 'SUI',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 4,
    color: '#4DA2FF',
    accentGradient: 'from-blue-500 to-cyan-400',
    description: 'High-performance Layer 1 blockchain powered by Move programming language.',
  },
  {
    id: 'sol',
    name: 'Solana',
    symbol: 'SOLUSDT',
    displaySymbol: 'SOL / USDT',
    baseAsset: 'SOL',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 2,
    color: '#14F195',
    accentGradient: 'from-emerald-400 to-teal-500',
    description: 'Ultra-fast L1 blockchain built for mass adoption, high TPS, and DeFi hub.',
    category: 'solana',
    ecosystemRole: 'L1 Blockchain Foundation',
  },
  {
    id: 'jup',
    name: 'Jupiter',
    symbol: 'JUPUSDT',
    displaySymbol: 'JUP / USDT',
    baseAsset: 'JUP',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 4,
    color: '#F59E0B',
    accentGradient: 'from-amber-500 to-orange-500',
    description: 'Premier DEX aggregator, liquidity routing engine, and perpetual DEX on Solana.',
    category: 'solana',
    ecosystemRole: 'DEX Aggregator & Perps',
  },
  {
    id: 'met',
    name: 'Meteora',
    symbol: 'METUSDT',
    displaySymbol: 'MET / USDT',
    baseAsset: 'MET',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 4,
    color: '#F43F5E',
    accentGradient: 'from-rose-500 to-pink-500',
    description: 'Next-gen Dynamic Liquidity Market Maker (DLMM) infrastructure on Solana.',
    category: 'solana',
    ecosystemRole: 'DLMM & Dynamic Liquidity',
  },
  {
    id: 'jto',
    name: 'Jito',
    symbol: 'JTOUSDT',
    displaySymbol: 'JTO / USDT',
    baseAsset: 'JTO',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 4,
    color: '#A855F7',
    accentGradient: 'from-purple-500 to-violet-500',
    description: 'Leading Solana liquid staking protocol (JitoSOL) and MEV infrastructure network.',
    category: 'solana',
    ecosystemRole: 'MEV & Liquid Staking',
  },
  {
    id: 'pump',
    name: 'Pump.fun',
    symbol: 'PUMPUSDT',
    displaySymbol: 'PUMP / USDT',
    baseAsset: 'PUMP',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 6,
    color: '#06B6D4',
    accentGradient: 'from-cyan-400 to-teal-500',
    description: 'Viral Solana memecoin launchpad and bonding-curve swap protocol.',
    category: 'solana',
    ecosystemRole: 'Memecoin Launchpad & Swap',
  },
  {
    id: 'zec',
    name: 'Zcash',
    symbol: 'ZECUSDT',
    displaySymbol: 'ZEC / USDT',
    baseAsset: 'ZEC',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 2,
    color: '#F4B728',
    accentGradient: 'from-amber-400 to-yellow-500',
    description: 'Decentralized cryptocurrency focused on privacy and shielded transactions.',
  },
  {
    id: 'pengu',
    name: 'Pudgy Penguins',
    symbol: 'PENGUUSDT',
    displaySymbol: 'PENGU / USDT',
    baseAsset: 'PENGU',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 6,
    color: '#F97316',
    accentGradient: 'from-orange-400 to-amber-500',
    description: 'The native token of the global web3 Pudgy Penguins ecosystem and IP.',
  },
  // Bybit Tokens
  {
    id: 'mon',
    name: 'Monad (MON)',
    symbol: 'MONUSDT',
    displaySymbol: 'MON / USDT',
    baseAsset: 'MON',
    quoteAsset: 'USDT',
    exchange: 'bybit',
    bybitCategory: 'spot',
    precision: 5,
    color: '#836EF9',
    accentGradient: 'from-purple-500 to-indigo-500',
    description: 'Ultra-high throughput 10,000 TPS parallelized EVM Layer 1 ecosystem.',
  },
  {
    id: 'hype',
    name: 'Hyperliquid (HYPE)',
    symbol: 'HYPEUSDT',
    displaySymbol: 'HYPE / USDT',
    baseAsset: 'HYPE',
    quoteAsset: 'USDT',
    exchange: 'bybit',
    bybitCategory: 'spot',
    precision: 2,
    color: '#00D2B4',
    accentGradient: 'from-teal-400 to-cyan-500',
    description: 'Flagship decentralized perps orderbook and L1 chain with deep native liquidity.',
  },
  {
    id: 'hyper',
    name: 'Hyperlane (HYPER)',
    symbol: 'HYPERUSDT',
    displaySymbol: 'HYPER / USDT',
    baseAsset: 'HYPER',
    quoteAsset: 'USDT',
    exchange: 'bybit',
    bybitCategory: 'spot',
    precision: 5,
    color: '#EC4899',
    accentGradient: 'from-pink-500 to-rose-500',
    description: 'Modular interoperability framework connecting rollups and diverse blockchains.',
  },
];

export const TIMEFRAMES: { label: string; value: Timeframe; binanceInterval: string; bybitInterval: string }[] = [
  { label: '1m', value: '1m', binanceInterval: '1m', bybitInterval: '1' },
  { label: '5m', value: '5m', binanceInterval: '5m', bybitInterval: '5' },
  { label: '15m', value: '15m', binanceInterval: '15m', bybitInterval: '15' },
  { label: '1H', value: '1h', binanceInterval: '1h', bybitInterval: '60' },
  { label: '4H', value: '4h', binanceInterval: '4h', bybitInterval: '240' },
  { label: '1D', value: '1d', binanceInterval: '1d', bybitInterval: 'D' },
];

export const SOLANA_ECOSYSTEM_TOKEN_IDS = ['sol', 'jup', 'met', 'jto', 'pump'];
export const SOLANA_TOKENS: TokenConfig[] = TOKENS.filter((t) => t.category === 'solana');
export const GLOBAL_TOKENS: TokenConfig[] = TOKENS.filter((t) => t.category !== 'solana' || t.id === 'sol');

