import type { TokenConfig, Timeframe } from '../types/crypto';

export const TOKENS: TokenConfig[] = [
  // Binance Tokens
  {
    id: 'sui',
    name: 'Sui',
    symbol: 'SUIUSDT',
    displaySymbol: 'SUI / USDT',
    baseAsset: 'SUI',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 4,
    color: '#4DA2FF',
    accentGradient: 'from-blue-500 to-cyan-400',
    description: 'High-performance Layer 1 blockchain powered by Move programming language.',
  },
  {
    id: 'sol',
    name: 'Solana',
    symbol: 'SOLUSDT',
    displaySymbol: 'SOL / USDT',
    baseAsset: 'SOL',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 2,
    color: '#14F195',
    accentGradient: 'from-emerald-400 to-teal-500',
    description: 'Ultra-fast L1 blockchain built for mass adoption and decentralized finance.',
  },
  {
    id: 'zec',
    name: 'Zcash',
    symbol: 'ZECUSDT',
    displaySymbol: 'ZEC / USDT',
    baseAsset: 'ZEC',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 2,
    color: '#F4B728',
    accentGradient: 'from-amber-400 to-yellow-500',
    description: 'Decentralized cryptocurrency focused on privacy and shielded transactions.',
  },
  {
    id: 'pengu',
    name: 'Pudgy Penguins',
    symbol: 'PENGUUSDT',
    displaySymbol: 'PENGU / USDT',
    baseAsset: 'PENGU',
    quoteAsset: 'USDT',
    exchange: 'binance',
    precision: 6,
    color: '#F97316',
    accentGradient: 'from-orange-400 to-amber-500',
    description: 'The native token of the global web3 Pudgy Penguins ecosystem and IP.',
  },
  // Bybit Tokens
  {
    id: 'mon',
    name: 'Monad (MON)',
    symbol: 'MONUSDT',
    displaySymbol: 'MON / USDT',
    baseAsset: 'MON',
    quoteAsset: 'USDT',
    exchange: 'bybit',
    bybitCategory: 'spot',
    precision: 5,
    color: '#836EF9',
    accentGradient: 'from-purple-500 to-indigo-500',
    description: 'Ultra-high throughput 10,000 TPS parallelized EVM Layer 1 ecosystem.',
  },
  {
    id: 'hype',
    name: 'Hyperliquid (HYPE)',
    symbol: 'HYPEUSDT',
    displaySymbol: 'HYPE / USDT',
    baseAsset: 'HYPE',
    quoteAsset: 'USDT',
    exchange: 'bybit',
    bybitCategory: 'spot',
    precision: 2,
    color: '#00D2B4',
    accentGradient: 'from-teal-400 to-cyan-500',
    description: 'Flagship decentralized perps orderbook and L1 chain with deep native liquidity.',
  },
  {
    id: 'hyper',
    name: 'Hyperlane (HYPER)',
    symbol: 'HYPERUSDT',
    displaySymbol: 'HYPER / USDT',
    baseAsset: 'HYPER',
    quoteAsset: 'USDT',
    exchange: 'bybit',
    bybitCategory: 'spot',
    precision: 5,
    color: '#EC4899',
    accentGradient: 'from-pink-500 to-rose-500',
    description: 'Modular interoperability framework connecting rollups and diverse blockchains.',
  },
];

export const TIMEFRAMES: { label: string; value: Timeframe; binanceInterval: string; bybitInterval: string }[] = [
  { label: '1m', value: '1m', binanceInterval: '1m', bybitInterval: '1' },
  { label: '5m', value: '5m', binanceInterval: '5m', bybitInterval: '5' },
  { label: '15m', value: '15m', binanceInterval: '15m', bybitInterval: '15' },
  { label: '1H', value: '1h', binanceInterval: '1h', bybitInterval: '60' },
  { label: '4H', value: '4h', binanceInterval: '4h', bybitInterval: '240' },
  { label: '1D', value: '1d', binanceInterval: '1d', bybitInterval: 'D' },
];
